name: firebase
description: A new Flutter project.

publish_to: 'none'


version: 2.2.2+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  email_validator: ^2.1.17
  flutter_svg: ^2.0.5
  dynamic_color: ^1.6.3
  eo_color: ^0.0.4
  http: ^0.13.5
  html: ^0.15.0
  flutter_html: ^3.0.0-alpha.3
  convert: ^3.1.1
  url_launcher: ^6.0.9
  animated_text_kit: ^4.2.1
  google_mobile_ads: ^3.0.0
  flutter_map: ^3.1.0
  google_maps_flutter: ^2.2.6
  google_maps_place_picker_mb: ^3.0.1
  geolocator: ^9.0.2
  geocode: ^1.0.2
  flutter_spinkit: ^5.1.0
  geocoding: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flare_flutter: ^3.0.2
  flutter_native_splash: ^2.2.19
  google_sign_in: ^6.1.1
  shared_preferences: ^2.0.12
  fluttertoast: ^8.0.7
  camera: ^0.10.5+2
  provider: ^6.0.5
  barcode_scanner: ^3.2.4
  firebase_storage: ^11.2.1
  barcode: ^2.2.4
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^0.8.7+5
  barcode_widget: ^2.0.4
  flutter_staggered_animations: ^1.1.1
  firebase_messaging: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
  - assets/
  - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/avatar.png"

